extends RefCounted


var energy_counts: Dictionary = {}
var kyokoro_orientation: StringName = &""

# Additional Charakoro results generated by special Move orchestration.
# The normal kyokoro_orientation above is always roll #1.
var additional_kyokoro_orientations: Array = []
var opponent_kyokoro_orientation: StringName = &""
var opponent_kyokoro_roll_triggered: bool = false
var selected_opponent_move_name_id: StringName = &""
var opponent_enerkoro_roll_triggered: bool = false
var opponent_enerkoro_counts: Dictionary = {}
var opponent_enerkoro_face_ids: Array = []
var opponent_enerkoro_max_count: int = 0
var opponent_enerkoro_most_common_types: Array = []
var opponent_enerkoro_damage_bonus: int = 0


func set_energy_count(
    energy_type: StringName,
    count: int
) -> void:
    energy_counts[energy_type] = max(count, 0)


func get_energy_count(
    energy_type: StringName
) -> int:
    return int(
        energy_counts.get(energy_type, 0)
    )


func get_total_energy_count() -> int:
    var total: int = 0

    for raw_count: Variant in energy_counts.values():
        total += int(raw_count)

    return total



func set_additional_kyokoro_orientations(
    orientations: Array
) -> void:
    var normalized: Array = []

    for raw_orientation: Variant in orientations:
        normalized.append(
            StringName(
                raw_orientation
            )
        )

    additional_kyokoro_orientations = normalized


func get_all_kyokoro_orientations() -> Array[StringName]:
    var result: Array[StringName] = []

    if kyokoro_orientation != &"":
        result.append(
            kyokoro_orientation
        )

    result.append_array(
        additional_kyokoro_orientations
    )

    return result
