extends RefCounted

# Export-safe manifest for built-in JSON content.
const FILES_BY_DIRECTORY: Dictionary = {
    "dice_setups": [
        "articuno_default.json",
        "bulbasaur_default.json",
        "charmander_default.json",
        "eevee_default.json",
        "grimer_default.json",
        "mew_default.json",
        "moltres_default.json",
        "onix_default.json",
        "pikachu_default.json",
        "pinsir_default.json",
        "player_energy_dice_setup.json",
        "squirtle_default.json",
        "zapdos_default.json",
    ],
    "kyokoro_profiles": [
        "bulbasaur_stl_custom.json",
        "charmander_stl_custom.json",
        "eevee_stl_custom.json",
        "grimer_stl_custom.json",
        "mew_model_custom.json",
        "mew_stl_custom.json",
        "pikachu_stl_custom.json",
        "squirtle_stl_custom.json",
        "standard_equal.json",
    ],
    "kyokoro_results": [
    ],
    "move_cards": [
        "articuno_air_cutter_ebw01_024.json",
        "articuno_blizzard_storm_ebw01_023.json",
        "articuno_cold_breath_ebw01_028.json",
        "articuno_fly_ebw01_030.json",
        "articuno_freeze_dive_ebw01_026.json",
        "articuno_frozen_blade_ebw01_022.json",
        "articuno_ice_shot_ebw01_027.json",
        "articuno_ice_wing_ebw01_021.json",
        "articuno_roost_ebw01_025.json",
        "articuno_sheer_cold_ebw01_029.json",
        "bulbasaur_acid_spray_stw01_007.json",
        "bulbasaur_aroma_storm_stw01_000.json",
        "bulbasaur_assault_stw01_005.json",
        "bulbasaur_giga_drain_stw01_006.json",
        "bulbasaur_grass_knot_stw01_004.json",
        "bulbasaur_leech_seed_stw01_003.json",
        "bulbasaur_razor_leaf_stw01_002.json",
        "bulbasaur_vine_whip_stw01_001.json",
        "charmander_ember_stw02_001.json",
        "charmander_fire_fang_stw02_004.json",
        "charmander_flame_up_stw02_000.json",
        "charmander_flamethrower_stw02_003.json",
        "charmander_flare_storm_stw02_005.json",
        "charmander_heat_up_stw02_002.json",
        "charmander_metal_claw_stw02_007.json",
        "charmander_thunder_punch_stw02_006.json",
        "eevee_bite_stw05_007.json",
        "eevee_charm_stw05_006.json",
        "eevee_flop_stw05_004.json",
        "eevee_full_power_dash_stw05_005.json",
        "eevee_tackle_stw05_002.json",
        "eevee_tail_slap_stw05_001.json",
        "eevee_take_down_stw05_003.json",
        "grimer_harassment_venom_ebw01_059.json",
        "grimer_poison_gas_ebw01_051.json",
        "grimer_sludge_ring_ebw01_054.json",
        "grimer_sludge_tackle_ebw01_058.json",
        "grimer_sludge_toss_ebw01_052.json",
        "grimer_toxic_blast_ebw01_057.json",
        "grimer_toxic_heal_ebw01_053.json",
        "grimer_venom_punch_ebw01_055.json",
        "grimer_venom_slip_ebw01_056.json",
        "mew_barrier_stw06_003.json",
        "mew_confusion_stw06_001.json",
        "mew_memory_skip_stw06_004.json",
        "mew_psybeam_stw06_002.json",
        "mew_psychic_stw06_006.json",
        "mew_psyshot_stw06_005.json",
        "mew_reflection_stw06_007.json",
        "moltres_burn_up_ebw01_018.json",
        "moltres_fire_spin_ebw01_016.json",
        "moltres_fire_wing_ebw01_011.json",
        "moltres_flamethrower_ebw01_013.json",
        "moltres_flare_blitz_ebw01_014.json",
        "moltres_fly_ebw01_020.json",
        "moltres_heat_breath_ebw01_017.json",
        "moltres_heat_wave_ebw01_012.json",
        "moltres_hurricane_ebw01_015.json",
        "moltres_wing_rush_ebw01_019.json",
        "onix_gyro_ball_ebw01_045.json",
        "onix_hard_impact_ebw01_044.json",
        "onix_iron_tail_ebw01_050.json",
        "onix_ram_ebw01_046.json",
        "onix_rock_barrier_ebw01_049.json",
        "onix_rock_slide_ebw01_047.json",
        "onix_rock_throw_ebw01_042.json",
        "onix_rock_wall_ebw01_043.json",
        "onix_rocky_tackle_ebw01_041.json",
        "onix_wild_tackle_ebw01_048.json",
        "pikachu_critical_bolt_stw04_000.json",
        "pikachu_electric_rush_stw04_003.json",
        "pikachu_gnaw_stw04_001.json",
        "pikachu_iron_tail_stw04_007.json",
        "pikachu_thunder_shock_stw04_002.json",
        "pikachu_thunder_stw04_005.json",
        "pikachu_thunderbolt_stw04_004.json",
        "pikachu_volt_tackle_stw04_006.json",
        "pinsir_berserk_swing_ebw01_007.json",
        "pinsir_brick_break_ebw01_005.json",
        "pinsir_concentrate_ebw01_001.json",
        "pinsir_deadly_scissors_ebw01_009.json",
        "pinsir_endure_ebw01_002.json",
        "pinsir_guillotine_ebw01_004.json",
        "pinsir_horn_attack_ebw01_003.json",
        "pinsir_reckless_charge_ebw01_008.json",
        "pinsir_scissors_charge_ebw01_006.json",
        "pinsir_submission_ebw01_010.json",
        "squirtle_bubble_beam_stw03_005.json",
        "squirtle_hard_shell_prw01_3_08.json",
        "squirtle_hydro_rage_stw03_006.json",
        "squirtle_mud_shot_stw03_007.json",
        "squirtle_shell_attack_stw03_004.json",
        "squirtle_water_gun_stw03_001.json",
        "squirtle_water_pulse_stw03_003.json",
        "squirtle_withdraw_stw03_002.json",
        "zapdos_aerial_ace_ebw01_034.json",
        "zapdos_crushing_wing_ebw01_035.json",
        "zapdos_discharge_ebw01_038.json",
        "zapdos_dual_thunder_ebw01_036.json",
        "zapdos_electroarrow_ebw01_037.json",
        "zapdos_fly_ebw01_040.json",
        "zapdos_thunder_chain_ebw01_039.json",
        "zapdos_thunder_flash_ebw01_031.json",
        "zapdos_thunder_shock_ebw01_032.json",
        "zapdos_volt_rush_ebw01_033.json",
    ],
    "pokemon": [
        "articuno_eb01_a1.json",
        "articuno_eb01_b1.json",
        "bulbasaur_standard.json",
        "charmander_standard.json",
        "eevee_standard.json",
        "grimer_eb01_a1.json",
        "grimer_eb01_b1.json",
        "mew_standard.json",
        "moltres_eb01_a1.json",
        "moltres_eb01_b1.json",
        "onix_eb01_a1.json",
        "onix_eb01_b1.json",
        "pikachu_standard.json",
        "pinsir_eb01_a1.json",
        "pinsir_eb01_b1.json",
        "squirtle_standard.json",
        "zapdos_eb01_a1.json",
        "zapdos_eb01_b1.json",
    ],
    "loadouts": [
        "pikachu_default_loadout.json",
    ],
    "reference": [
        "condition_types.json",
        "effect_opcodes.json",
        "energy_types.json",
        "kyokoro_orientations.json",
        "pokemon_types.json",
        "rule_triggers.json",
    ],
    "rules": [
        "battle_rules.json",
        "team_builder_rules.json",
    ],
}

const ROOT_JSON_FILES: Array[String] = [
    "catalog.json",
    "kyokoro_orientation_map.json",
]

static func files_for(directory_name: String) -> Array[String]:
    var raw: Variant = FILES_BY_DIRECTORY.get(directory_name, [])
    var result: Array[String] = []
    if raw is Array:
        for item: Variant in raw:
            result.append(String(item))
    return result


static func ids_for(directory_name: String) -> Array[String]:
    var result: Array[String] = []
    for file_name: String in files_for(directory_name):
        if file_name.ends_with(".json"):
            result.append(file_name.trim_suffix(".json"))
    return result
